# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produtos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
