# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('cnpj', models.BigIntegerField(verbose_name='CNPJ')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
