# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cidade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.BigIntegerField(blank=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.BigIntegerField(unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='estado',
            field=models.CharField(blank=True, max_length=20, verbose_name='Estado'),
        ),
    ]
