# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180313_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.BigIntegerField(blank=True, verbose_name='CNPJ'),
        ),
    ]
