# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180314_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
