# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_auto_20180411_1540'),
        ('client', '0005_auto_20180314_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('produtos', models.ManyToManyField(to='produtos.Produtos')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'verbose_name': 'Pedido',
            },
        ),
    ]
