# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(default='Aberto', max_length=30, verbose_name='Status'),
        ),
    ]
