# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20180604_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='produtos',
            field=models.ManyToManyField(related_name='produtos', to='produtos.Produtos'),
        ),
    ]
