# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20180517_1246'),
        ('pedidos', '0004_auto_20180606_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Tamanho ou Medida')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name_plural': 'Itens da Compra',
                'verbose_name': 'Item da Compra',
            },
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_total',
            field=models.FloatField(blank=True, default=0, verbose_name='Valor total'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.Pedidos', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos'),
        ),
    ]
